#ifdef T_EMBED_1101
#include "lilygo-t-embed-cc1101.h"
#elif T_EMBED
#include "lilygo-t-embed.h"
#elif T_DECK
#include "lilygo-t-deck.h"
#elif ARDUINO_M5STACK_CARDPUTER
#include "m5stack-cardputer.h"
#elif CYD_2432S028
#include "CYD-2432S028.h"
#elif ARDUINO_M5STACK_CORE
#include "m5stack-core.h"
#elif ARDUINO_M5STACK_CORES3
#include "m5stack-cores3.h"
#elif ARDUINO_M5STACK_CORE2
#include "m5stack-core2.h"
#elif ARDUINO_M5STICK_C_PLUS
#include "m5stack-cplus1_1.h"
#elif ARDUINO_M5Stick_C
#include "m5stack-c.h"
#elif ARDUINO_M5STICK_C_PLUS2
#include "m5stack-cplus2.h"
#elif ESP32S3DEVKITC1
#include "ESP32S3-General.h"
#elif ESP32S3_4M
#include "ESP32S3-4M.h"
#elif ESP32_DEV
#include "esp32dev.h"
#elif MARAUDERMINI
#include "marauder-mini.h"
#elif MARAUDERV4
#include "marauder-v4og.h"
#elif T_DISPLAY_S3_TOUCH
#include "lilygo-t-display-s3-touch.h"
#elif T_DISPLAY_S3_PRO
#include "lilygo-t-display-s3-pro.h"
#elif SMOOCHIEE_BOARD
#include "smoochiee-board.h"
#endif